import type { BlogPost, TeamMember, Achievement } from '../types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Campeonato Departamental 2025: TaoTeKing arrasa con 12 medallas',
    slug: 'campeonato-departamental-2025',
    excerpt: 'Nuestros atletas demostraron su nivel en el Campeonato Departamental, logrando 7 oros, 3 platas y 2 bronces en diferentes categorías.',
    content: `El pasado fin de semana, el Club TaoTeKing participó en el Campeonato Departamental de Taekwondo 2025, donde nuestros atletas brillaron con luz propia obteniendo un total de 12 medallas.\n\nLa delegación estuvo conformada por 20 deportistas de diferentes categorías de edad, desde infantil hasta mayores, quienes demostraron el fruto de meses de arduo entrenamiento.\n\nEn la categoría infantil, destacó especialmente la actuación de nuestros más jóvenes competidores, quienes enfrentaron a rivales de mayor experiencia con valentía y técnica impecable.\n\nEl maestro fundador expresó su orgullo: "Este resultado es el reflejo del compromiso de cada uno de nuestros atletas y sus familias. Seguiremos trabajando para el próximo campeonato nacional."`,
    category: 'competencias',
    coverImage: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=80',
    author: 'Maestro Carlos Rodríguez',
    publishedAt: '2025-11-15',
    tags: ['campeonato', 'medallas', 'competencia', 'logros'],
    featured: true,
  },
  {
    id: '2',
    title: 'Ceremonia de Graduación: 15 nuevos cinturones de colores',
    slug: 'ceremonia-graduacion-cinturones-2025',
    excerpt: 'Con gran emoción, 15 de nuestros estudiantes avanzaron a un nuevo nivel en su camino del Taekwondo durante la ceremonia de graduación del mes.',
    content: `La ceremonia de graduación realizada en nuestras instalaciones fue un momento de gran emoción para toda la familia TaoTeKing. Quince estudiantes de diferentes edades demostraron ante jueces y familiares su progreso en la práctica del Taekwondo.\n\nCada examinando presentó las formas (poomsae) correspondientes a su nivel, así como técnicas de patadas y rompimiento de tablas, evidenciando el trabajo constante durante los últimos meses.\n\nFelicitamos a todos los nuevos graduados y los motivamos a continuar en su camino de superación personal a través de las artes marciales.`,
    category: 'actividades',
    coverImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
    author: 'Admin TaoTeKing',
    publishedAt: '2025-10-28',
    tags: ['graduación', 'cinturones', 'estudiantes', 'progreso'],
    featured: true,
  },
  {
    id: '3',
    title: 'Técnica del mes: La patada giratoria hacia atrás',
    slug: 'tecnica-patada-giratoria-atras',
    excerpt: 'Exploramos en detalle una de las técnicas más espectaculares del Taekwondo: la patada giratoria hacia atrás, sus variantes y cómo entrenarla de forma segura.',
    content: `La patada giratoria hacia atrás (Dwi Dollyo Chagi) es una de las técnicas más poderosas y espectaculares del Taekwondo. En este artículo, nuestros instructores explican los fundamentos para ejecutarla correctamente.\n\n**Preparación:** Antes de intentar esta técnica, es fundamental tener un calentamiento adecuado y flexibilidad en cadera y piernas.\n\n**Posición inicial:** Parte desde una postura de combate, con el pie de pateo ligeramente atrasado.\n\n**Ejecución:** La rotación comienza desde los hombros, los ojos localizan el objetivo y la pierna se lanza en un movimiento circular explosivo.\n\n**Seguridad:** Siempre practícala primero en velocidad lenta y con supervisión de tu instructor.`,
    category: 'tecnica',
    coverImage: 'https://images.unsplash.com/photo-1509155194946-c1f45d2f1a4b?w=800&q=80',
    author: 'Instructor Andrés Mesa',
    publishedAt: '2025-10-10',
    tags: ['técnica', 'patada', 'entrenamiento', 'formación'],
    featured: false,
  },
  {
    id: '4',
    title: 'Taller de Defensa Personal para Mujeres - ¡Únete!',
    slug: 'taller-defensa-personal-mujeres',
    excerpt: 'Próximo sábado realizamos un taller gratuito de defensa personal dirigido a mujeres de todas las edades. Inscríbete ahora.',
    content: `Desde TaoTeKing, nos comprometemos con la seguridad y empoderamiento de nuestra comunidad. Por eso, el próximo sábado ofrecemos un taller gratuito de defensa personal especialmente diseñado para mujeres.\n\nEl taller cubrirá técnicas básicas de autoprotección, conciencia situacional y cómo reaccionar ante diferentes escenarios de riesgo.\n\nNo se requiere experiencia previa. Cupo limitado a 30 participantes. Inscríbete enviando un mensaje a nuestras redes sociales.`,
    category: 'actividades',
    coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    author: 'Admin TaoTeKing',
    publishedAt: '2025-09-20',
    tags: ['taller', 'defensa personal', 'mujeres', 'comunidad'],
    featured: false,
  },
  {
    id: '5',
    title: 'Nuestro atleta Juan Pérez, clasificado al Campeonato Nacional',
    slug: 'juan-perez-clasificado-nacional',
    excerpt: 'Con una actuación brillante en el torneo zonal, nuestro deportista Juan Pérez logró la clasificación al Campeonato Nacional de Taekwondo 2026.',
    content: `Es un motivo de gran orgullo para todo el Club TaoTeKing informar que nuestro destacado atleta Juan Pérez ha logrado la clasificación al Campeonato Nacional de Taekwondo que se celebrará en enero de 2026.\n\nJuan, de 19 años y cinturón negro 2do Dan, superó a 8 rivales en el torneo zonal con una actuación impecable, mostrando su poderío técnico y táctica de combate.\n\n"Estoy muy agradecido con el club y con el maestro por todo el apoyo. Ahora hay que seguir entrenando fuerte para representar bien en el nacional", comentó el atleta.`,
    category: 'logros',
    coverImage: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=800&q=80',
    author: 'Admin TaoTeKing',
    publishedAt: '2025-09-05',
    tags: ['logros', 'clasificación', 'nacional', 'atleta'],
    featured: true,
  },
  {
    id: '6',
    title: 'Inicio de nueva temporada: horarios y matriculas 2026',
    slug: 'nueva-temporada-horarios-2026',
    excerpt: 'Todo lo que necesitas saber sobre la nueva temporada: horarios, tarifas y proceso de inscripción.',
    category: 'noticias',
    content: `Nos preparamos para comenzar una nueva y emocionante temporada. Aquí te presentamos toda la información que necesitas.\n\n**Horarios de entrenamiento:**\n- Infantil (6-12 años): Lunes, Miércoles y Viernes 4:00 PM - 5:30 PM\n- Juvenil (13-17 años): Lunes, Miércoles y Viernes 5:30 PM - 7:00 PM\n- Adultos y competencia: Martes, Jueves y Sábados 6:00 PM - 8:00 PM\n\n**Proceso de matrícula:**\nLas inscripciones para nuevos estudiantes están abiertas. Visítanos en nuestras instalaciones o contáctanos por redes sociales para más información.`,
    coverImage: 'https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=800&q=80',
    author: 'Admin TaoTeKing',
    publishedAt: '2025-08-15',
    tags: ['horarios', 'matrícula', 'nueva temporada', '2026'],
    featured: false,
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Maestro Carlos Rodríguez',
    role: 'Fundador y Director Técnico',
    belt: 'Cinturón Negro',
    dan: 6,
    bio: 'Con más de 25 años de experiencia en el Taekwondo, el Maestro Carlos fundó TaoTeKing con la visión de crear un espacio donde las artes marciales transformen vidas. Campeón nacional en 3 ocasiones y formador de numerosos campeones.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    socialLinks: { instagram: '#', facebook: '#' },
  },
  {
    id: '2',
    name: 'Instructora María López',
    role: 'Instructora Principal - Infantil y Juvenil',
    belt: 'Cinturón Negro',
    dan: 3,
    bio: 'Especialista en enseñanza para niños y jóvenes, María lleva 10 años dedicada a la formación de las nuevas generaciones. Su metodología pedagógica hace que el aprendizaje sea divertido y efectivo.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    socialLinks: { instagram: '#' },
  },
  {
    id: '3',
    name: 'Instructor Andrés Mesa',
    role: 'Instructor de Competencia',
    belt: 'Cinturón Negro',
    dan: 4,
    bio: 'Ex-seleccionado nacional, Andrés es el encargado de preparar a nuestros atletas de alto rendimiento. Su expertise en análisis táctico y preparación física hace la diferencia en competencia.',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    socialLinks: { instagram: '#', facebook: '#' },
  },
  {
    id: '4',
    name: 'Instructora Sofia Herrera',
    role: 'Instructora de Poomsae y Fitness',
    belt: 'Cinturón Negro',
    dan: 2,
    bio: 'Campeona regional de Poomsae, Sofia combina el arte de las formas tradicionales con técnicas modernas de acondicionamiento físico, ofreciendo clases dinámicas y técnicamente rigurosas.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    socialLinks: { instagram: '#' },
  },
];

export const achievements: Achievement[] = [
  { id: '1', title: 'Campeonato Nacional - Categoría Juvenil', year: 2024, description: 'Medalla de oro en la categoría juvenil masculino -55kg', type: 'oro', athlete: 'Juan Pérez' },
  { id: '2', title: 'Campeonato Departamental', year: 2024, description: '12 medallas en total: 7 oros, 3 platas y 2 bronces', type: 'especial' },
  { id: '3', title: 'Copa Internacional Ciudad de Medellín', year: 2023, description: 'Medalla de plata en Poomsae categoría femenina adulto', type: 'plata', athlete: 'Sofia Herrera' },
  { id: '4', title: 'Campeonato Nacional - Categoría Infantil', year: 2023, description: 'Medalla de bronce en categoría infantil femenino', type: 'bronce', athlete: 'Valentina Ríos' },
  { id: '5', title: 'Mejor Club del Departamento', year: 2022, description: 'Reconocimiento a la institución con mayor proyección deportiva del año', type: 'especial' },
  { id: '6', title: 'Copa Regional Andina', year: 2022, description: 'Primer lugar en la clasificación por puntos en la Copa Regional', type: 'oro' },
];
